python3 simple_sim.py --shape rect1 --vis 1
python3 simple_sim.py --shape rect2 --vis 1
python3 simple_sim.py --shape rect3 --vis 1
python3 simple_sim.py --shape ellip1 --vis 1
python3 simple_sim.py --shape ellip2 --vis 1
python3 simple_sim.py --shape ellip3 --vis 1
python3 simple_sim.py --shape hex --vis 1
python3 simple_sim.py --shape tri1 --vis 1
python3 simple_sim.py --shape tri2 --vis 1
python3 simple_sim.py --shape tri3 --vis 1
